### ISSUE TITLE
No command works with pygame 3.7

### ISSUE THREAD

**Issue by LtOJ** [pygame/pygame#696]
Pygame is installed and up to date. It is also the correct version. No other functions seem to to work either :/

#CODE
import pygame
pygame.display.set_mode([800, 600])

#ERROR
"""
Traceback (most recent call last):
  File "C:\PythonPrograms\37\pygame.py", line 1, in <module>
    import pygame
  File "C:\PythonPrograms\37\pygame.py", line 2, in <module>
    screen = pygame.display.set_mode([800, 600])
AttributeError: 'module' object has no attribute 'display'
"""

**Comment by illume** [comment]
Do you have a file called pygame.py?

**Comment by LtOJ** [comment]
Thank you so much. I'm new to pygame and programming in general. This saved a lot of stress.
