### ISSUE TITLE
Update display.toggle_fullscreen() docs for pygame 2

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1990]
Currently the toggle_fullscreen() contain these lines:

> This function only works under the UNIX X11 video driver. For most situations it is better to call pygame.display.set_mode() with new display flags.

This is no longer accurate as the function works on windows for sure (tested) and looking at the code likely works on mac and with other display drivers on linux too. I believe it is also a more reliable method now to switch to full screen than calling `set_mode()` twice.

I propose removing the two lines above and instead having two sections, one for pygame 1 and one for pygame 2 declaring which platforms support the function. Something like:

>Switches the display window between windowed and fullscreen modes.
>
> **Supported display drivers in pygame 1**
> - x11 (Linux/Unix)
>
>**Supported display drivers in pygame 2**
> - windows (Windows)
> - x11 (Linux/Unix)
> - wayland (Linux/Unix)
> - cocoa (OSX/Mac)

**To Do**

- [x] Check `toggle_fullscreen()` support on windows in 2.0.0.dev10
- [x] Check `toggle_fullscreen()` support on linux (x11) in 2.0.0.dev10
- [x] Check `toggle_fullscreen()` support on linux (wayland) in 2.0.0.dev10
- [x] Check `toggle_fullscreen()` support on mac (cocoa) in 2.0.0.dev10
- [x] Check `toggle_fullscreen()` support on mac (metal) in 2.0.0.dev10
 - [x] Check `toggle_fullscreen()` support on windows in 1.9.6
- [x] Check `toggle_fullscreen()` support on linux (x11) in 1.9.6
- [x] Check `toggle_fullscreen()` support on linux (wayland) in 1.9.6
- [x] Check `toggle_fullscreen()` support on mac (cocoa) in 1.9.6
- [x] Check `toggle_fullscreen()` support on mac (metal) in 1.9.6
- [ ] After testing, update docs deleting lines and adding supported platform results as above.

**Comment by galexandreg** [comment]
I thought I would test this on mac, but I'm not sure I understand the cocoa and metal distinction.
I just started playing with the SDL, but the way I understand it, cocoa is the video driver, like X11 and Wayland on linux, and Metal is a renderer driver, like opengl. Looking at the toggle_fullscreen code, the video driver is always cocoa on mac, but the behavior of toggle_fullscreen is different whether the window is displaying a software surface, an SDL renderer (metal, opengl, software) or open gl stuff. Perhaps there's something I don't understand.

---

- **From what I tested, it works fine on the latest mac os with 2.0.0.dev10.**
I tested with a **normal software window**, **pygame.OPENGL** and **pygame.SCALED** (SDL renderer)

I think the docs should explain that the behavior is different with a normal window and with pygame.SCALED.

- With pygame.SCALED, the system resolution doesn't change (SDL_WINDOW_FULLSCREEN_DESKTOP), and the SDL does all the scaling (even for the mouse input). There is nothing to change in the program and everything works.

- With a normal window, it tries to change the system resolution (SDL_WINDOW_FULLSCREEN) to the pygame window, and it will only work with some supported "standard" resolutions. It's also up to the programmer to manage everything.

**Comment by galexandreg** [comment]
I was bored, so I tested it on Linux with my Raspberry Pi (**X11**) 😃 

**Everything works as expected with Pygame 1 and 2**. (normal windows, pygame.OPENGL and pygame.SCALED)
With Pygame1, the behavior is different. It will simply center the contents and put a black border around it. With Pygame2, it does the same as on mac os.

**Comment by MyreMylar** [comment]
Thanks for the testing reports! I ticked them off.

Seems like the basic overview so far is:

**Supported display drivers in pygame 1**

x11 (Linux/Unix)

**Supported display drivers in pygame 2**

windows (Windows)
x11 (Linux/Unix)
cocoa (OSX/Mac)

With wayland on linux and windows 1.9.6 still to test.

I don't know much about mac video drivers myself, I was mostly guessing. Probably the distinction doesn't matter in the way I thought it might for this - which is good because it makes the picture simpler.

**Comment by zoldalma999** [comment]
Hi!
I tested it on Windows 10 with 1.9.6 with both normal window and pygame.OPENGL
It returned 0 and did nothing else.

**Comment by MyreMylar** [comment]
> I tested it on Windows 10 with 1.9.6 with both normal window and pygame.OPENGL
It returned 0 and did nothing else.

Thanks! That's about what was expected for 1.9.6 on windows. I've ticked it off the list.

**Comment by twistios** [comment]
Hello, this is my first issue. Actually I don't have a Wayland-Distro, but I am setting-up one right now (in a virtual machine). If I need to mind something special, please tell me about it.

**Comment by galexandreg** [comment]
The code for toggle_fullscreen works for three different types of windows (Normal, pygame.SCALED and OpenGL). I think you should test them all.

- Pygame 1.9.6
  - Normal window
  - Opengl window
- Pygame 2
  - Normal window
  - Opengl window
  - Pygame.SCALED window

It should not work for pygame 1 (it's X11 only)
With pygame 2, the results should be similar than the ones I poster earlier from my mac tests.

The unittest is only testing normal software windows.

**Comment by twistios** [comment]
Pygame 1.9.6(Wayland using Fedora):
-normal window: It seams to work
-opengl: having problems setting up the Opengl test, but it seams not to be a problem with pygame.

Error:
`OpenGL.error.NullFunctionError: Attempt to call an undefined function gluPerspective, check for bool(gluPerspective) before calling`

If I follow what it says, no extra Errors are coming, but the code does not work. I tested the same code on Windows 10. There it worked, but `toggle_fullscreen` did not work as I expected.

I currently did not test Pygame 2, I will do it, once I solved the Opengl issue, as Opengl currently does not work, so I can not test it.

**Comment by galexandreg** [comment]
I can't really help you with OpenGL issues, but you could try the glcube.py program in the examples folder (and modify it to use toggle_fullscreen). That way we would know if it's caused by your testing code or by something else.

**Comment by twistios** [comment]
It is having the same problems with `pygame.example.glcube`.

**Comment by MyreMylar** [comment]
The OpenGL issue is because the glcube example only works with old-skool openGL in 1.9.6.

 To fix it you just need to replace the code in glcube.py with the current code which you can just copy and paste from github here:

https://raw.githubusercontent.com/pygame/pygame/master/examples/glcube.py

**Comment by twistios** [comment]
I am using pyopengl 3.1.5 on both Windows and (virtual) Fedora.
On Windows it's opengl 4.5, and the example works (with Pygame 1.9.6, my opengl version has support for older versions).
On Fedora it's opengl 3.1, the example does not work (with Pygame 1.9.6).

It now says: `AttributeError: module 'pygame' has no attribute 'GL_CONTEXT_MAJOR_VERSION'`, when I am using the code you suggested me.
