### ISSUE TITLE
Sphinx docs download issues

### ISSUE THREAD

**Issue by BradTFT** [pygame/pygame#3200]
Hi,

I am going to be travelling soon and wanted to get a local copy of the documentation. I noticed the README in the docs folder and tried it. (im not sure if this is the right place to be putting this issue please correct me if im wrong). I installed Sphinx and forked the repo. cloned it into a folder and `cd pygame-docs-fork`. ran `python3 setup.py docs` and got this error

```
python3 setup.py docs
Traceback (most recent call last):
  File "/home/BradTFT/fork/pygame-docs-fork/setup.py", line 72, in <module>
    from setuptools import setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 35, in <module>
    from setuptools.depends import Require
  File "/usr/lib/python3/dist-packages/setuptools/depends.py", line 7, in <module>
    from .py33compat import Bytecode
  File "/usr/lib/python3/dist-packages/setuptools/py33compat.py", line 55, in <module>
    unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

i tried running `python3 setup.py docs --f` and got the same error. currently on Sphinx version ```Sphinx                        1.8.6
sphinxcontrib-websupport      1.1.2``` and python3 version 3.9.2. Not sure what else i can try for troubleshooting besides making this issue. forums were no help.

**Comment by Starbuck5** [comment]
We don't build on Sphinx 1.0 anymore. You need Sphinx 2, but Sphinx 4 is where we generate ours.
(All that is off the top of my head so it may be wrong)

On pygame 2.1.2 you can just `python -m pygame.docs` and it will launch the locally included copy of the documentation. We bundle documentation in our distribution through pip.

**Comment by BradTFT** [comment]
so what should i do abt my sphinx version? just leave it and attempt the command mentioned?

**Comment by ankith26** [comment]
Yeah, that should work

**Comment by BradTFT** [comment]
awesome. i appreciate the help. fastest thats ever gone
