### ISSUE TITLE
texture_sprite example broken by #1724

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#2056]
I noticed that my texture sprite test fails in dev10. The same error occurs with examples/texture_sprite.py. The error code is as follows:
```
Traceback (most recent call last):
  File "sdl2test.py", line 174, in <module>
    group.draw(renderer)
  File "/home/michael/.local/lib/python3.7/site-packages/pygame/sprite.py", line 477, in draw
    surface.blits((spr.image, spr.rect) for spr in sprites)
AttributeError: 'pygame._sdl2.video.Renderer' object has no attribute 'blits'
```
JoKing recommended I submit this issue even though it uses to the experimental sdl2_render api. He suggested that the error relates to #1724 and will be an easy fix. I concur.
