### ISSUE TITLE
Cannot install under Python 3.14

### ISSUE THREAD

**Issue by DigitalDetective47** [pygame/pygame#4627]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** : Windows
- **Python version** : CPython 3.14.0

**Current behavior:**

Attempting to install pygame on Python 3.14.0 causes an error. It installs just fine on Python 3.13.9.

**Screenshots**

```
PS C:\Windows\System32> py -3.14 -m pip install pygame
Collecting pygame
  Using cached pygame-2.6.1.tar.gz (14.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
      Skipping Cython compilation


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.28.4-VC.zip 25ef9d201ce3fd5f976c37dddedac36bd173975c
      Unzipping :prebuilt_downloads\SDL2-devel-2.28.4-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-devel-2.20.1-VC.zip 371606aceba450384428fd2852f73d2f6290b136
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.20.1-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-VC.zip 000e3ea8a50261d46dbd200fb450b93c59ed4482
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.6.2-VC.zip:
      Downloading... https://github.com/pygame/pygame/releases/download/2.1.3.dev4/prebuilt-x64-pygame-2.1.4-20220319.zip 16b46596744ce9ef80e7e40fa72ddbafef1cf586
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-2.1.4-20220319.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.28.4
      ...Library directory for SDL: prebuilt-x64/SDL2-2.28.4/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.28.4/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.28.4/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE: prebuilt-x64
      ...Library directory for FREETYPE: prebuilt-x64/lib
      ...Include directory for FREETYPE: prebuilt-x64/include
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/lib/freetype.dll
      DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      Traceback (most recent call last):
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\vstools.py", line 4, in <module>
          from distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'distutils.msvccompiler'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\vstools.py", line 6, in <module>
          from setuptools._distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'setuptools._distutils.msvccompiler'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\vstools.py", line 4, in <module>
          from distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'distutils.msvccompiler'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ninji\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "C:\Users\ninji\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ninji\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ninji\AppData\Local\Temp\pip-build-env-chvy04o4\overlay\Lib\site-packages\setuptools\build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ninji\AppData\Local\Temp\pip-build-env-chvy04o4\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\ninji\AppData\Local\Temp\pip-build-env-chvy04o4\overlay\Lib\site-packages\setuptools\build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ninji\AppData\Local\Temp\pip-build-env-chvy04o4\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 432, in <module>
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\config.py", line 234, in main
          deps = CFG.main(**kwds, auto_config=auto)
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\config_win.py", line 493, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
          DEPS.configure()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\config_win.py", line 338, in configure
          from buildconfig import vstools
        File "C:\Users\ninji\AppData\Local\Temp\pip-install-05wqv99y\pygame_fc7ee1d6da7e4e6e907dd6522e51f545\buildconfig\vstools.py", line 6, in <module>
          from setuptools._distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'setuptools._distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'pygame' when getting requirements to build wheel
```
```
PS C:\Windows\System32> py -3.13 -m pip install pygame
Collecting pygame
  Downloading pygame-2.6.1-cp313-cp313-win_amd64.whl.metadata (13 kB)
Downloading pygame-2.6.1-cp313-cp313-win_amd64.whl (10.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 74.9 MB/s  0:00:00
Installing collected packages: pygame
Successfully installed pygame-2.6.1
```

**Comment by SecretBrain** [comment]
met the same issue w/ 3.14 as well.

**Comment by TekGeek2003** [comment]
I'm having the same issue with 3.14.0

**Comment by chopperflyer** [comment]
I have also had this issue on Windows when installing in CMD.  The error reports that the issue is with building the wheel.  I have attempted the fix of using a previous version as suggested in #3522 and this did not work.  I have confirmed that my Python is correctly installed and added to path.  I am at a loss as to next steps and would appreciate any suggestions.  I am happy to go to a previous version of python yet evidence suggests that this has been going on for several years (#3673 and #3522 are all older issue tickets) so am not sure what version this will work on if at all as it seems to be more of an issue with missing components with windows.   I am still in my coding infancy so any help or guidance would be very much appreciated.

**Comment by sanamasako** [comment]
Sorry if I sound like I'm stating the obvious here, but I feel like the reason why it's not working with 3.14 is because changes were made (for example, the syntax is slightly different; 3.12 made similar changes) that would cause pygame to not work, so it's being rejected by Python. I tried getting around the wheel building issue by downloading a pre-made one and having pip try to install that, but it outright told me it's not compatible. Pygame is going to have to release a 2.6.2 (or a 2.7) that works with Python 3.14. I personally wouldn't call this a bug, as it's kinda normal for stuff to cause issues upon updating. Just gotta stick with Python 3.13.9 for the time being.

**Comment by MichaelRochaPy** [comment]
i had the same issue in py 3.14.

**Comment by adamwesterman89-web** [comment]
If you are using windows, install python 3.12 in the Microsoft store and then use the following command in the terminal:

py -3.12 -m pip install pygame

Make sure that your IDE is setup to use python 3.12. That's what fixed it for me.

**Comment by Kaszanas** [comment]
This is the key issue: https://github.com/pypa/setuptools/issues/4620#issuecomment-2325659051

Pygame seems to be using deprecated functions here:

https://github.com/pygame/pygame/blob/85fda3f719d437cf27106afae8c890e6b88ba5f5/buildconfig/vstools.py#L3-L6

Apparently there is one PR that attempts to add Python 3.14 support #4546 but at the same time CI fails.

More on this: https://docs.python.org/3/library/distutils.html

**Comment by sanamasako** [comment]
Ah, good old deprecations. Is this the only issue?

**Comment by Kaszanas** [comment]
> Ah, good old deprecations. Is this the only issue?

It's hard to say. Apparently installing `setuptools<70` might help, but then I got hit with an issue with the comliler. It'd be best for someone a little more knowledgeable to speak up and produce builds.

I was trying to build for 3.13t and 3.14t

**Comment by deenbee** [comment]
The community really needs an urgent update to PyGame to take advantage of the potential of Python 3.14. Thanks, we're waiting for that update. Let's go PyGame soon.

**Comment by alpargun** [comment]
Same issue with MacOS (M4)

`(pointmassnavigationrl) alp@Alps-MacBook-Pro pointMassNavigationRL % uv add 'stable-baselines3[extra]'
Resolved 133 packages in 85ms
  × Failed to build `pygame==2.6.1`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]
      Skipping Cython compilation

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/MacCompile
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---


      [stderr]
      src_c/_sdl2/sdl2.c:1237:10: fatal error: 'SDL.h' file not found
       1237 | #include "SDL.h"
            |          ^~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1

      hint: This error likely indicates that you need to install a library that provides "SDL.h" for `pygame@2.6.1`
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncing.`

**Comment by DigitalDetective47** [comment]
that seems to be a different issue. can you confirm that it compiles correctly on python 3.13?

**Comment by alpargun** [comment]
Yes

**Comment by vagueacid** [comment]
It works with 3.13.9, just had to install that version.

**Comment by konbraphat51** [comment]
I already fixed this for months ago in https://github.com/pygame/pygame/pull/4538, but the problem is the maintainers keep ignoring this

**Comment by derDere** [comment]
> not relevant

sorry wrong Issue let me delete that.

**Comment by fyardlest1** [comment]
Alternatively you can use pygame-ce: pip install pygame-ce

**Comment by MyslZhao** [comment]
same with 1.14.4

**Comment by DigitalDetective47** [comment]
> same with 1.14.4

1.14.4 of what? this issue is documenting Pygame 2.6.1 on Python 3.14.0

**Comment by TekGeek2003** [comment]
> > same with 1.14.4
> 
> 1.14.4 of what? this issue is documenting Pygame 2.6.1 on Python 3.14.0

Download Pygame-ce it's a way better version.

**Comment by MyslZhao** [comment]
> > same with 1.14.4
> 
> 1.14.4 of what? this issue is documenting Pygame 2.6.1 on Python 3.14.0

sorry ,it's 3.14.4😅

**Comment by DigitalDetective47** [comment]
![Image](https://github.com/user-attachments/assets/047430e3-c073-475c-8894-ece5f747f17f)

**Comment by Faizens** [comment]
Fix it already. Im using 1.14.2 .Cant install pygame

**Comment by DreamChaser55** [comment]
Still getting this. Pygame cannot be used on Windows with Python 3.14.
